export const shellStyles = {
  wrapper: {
    minH: '100vh',
    background: 'var(--page-bg-gradient)',
    color: 'var(--text-main)',
    transition: 'background 180ms ease, color 180ms ease',
  },
  content: {
    position: 'relative',
  },
}

export const brandLogoStyles = {
  link: {
    display: 'inline-flex',
    alignItems: 'center',
  },
  frame: {
    w: { base: '11.2rem', md: '12.8rem' },
    h: { base: '3.6rem', md: '4.12rem' },
    overflow: 'hidden',
    borderRadius: '1rem',
    border: '1px solid var(--surface-line)',
    bg: 'var(--logo-frame-bg)',
    boxShadow: 'var(--shadow-soft)',
  },
  image: {
    w: '100%',
    h: '100%',
    objectFit: 'contain',
    objectPosition: 'center',
  },
}

export const profileMenuStyles = {
  wrapper: {
    position: 'fixed',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    top: { base: '1rem', md: '1.4rem' },
    right: { base: '1rem', md: '1.4rem' },
    zIndex: 30,
  },
  trigger: {
    position: 'relative',
    display: 'grid',
    placeItems: 'center',
    w: '3.2rem',
    h: '3.2rem',
    borderRadius: 'full',
    border: '1px solid var(--surface-line)',
    bg: 'var(--profile-trigger-bg)',
    boxShadow: 'var(--shadow-soft)',
    backdropFilter: 'blur(14px)',
    transition: 'transform 180ms ease, background 180ms ease',
    _hover: {
      transform: 'translateY(-2px)',
      bg: 'var(--profile-trigger-hover)',
    },
  },
  avatarHead: {
    position: 'absolute',
    top: '0.72rem',
    w: '0.92rem',
    h: '0.92rem',
    borderRadius: 'full',
    bg: 'var(--text-main)',
  },
  avatarBody: {
    position: 'absolute',
    bottom: '0.62rem',
    w: '1.5rem',
    h: '0.95rem',
    borderRadius: '999px 999px 0.5rem 0.5rem',
    bg: 'var(--text-main)',
  },
  panel: {
    mt: '3',
    w: { base: '16rem', md: '18rem' },
    ml: 'auto',
    p: '4',
    borderRadius: '1.25rem',
    border: '1px solid var(--surface-line)',
    bg: 'var(--surface-strong)',
    backdropFilter: 'blur(18px)',
    boxShadow: 'var(--shadow)',
  },
  panelTitle: {
    fontSize: 'sm',
    fontWeight: '700',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--text-main)',
  },
  panelCopy: {
    mt: '2',
    color: 'var(--text-soft)',
    fontSize: 'sm',
    lineHeight: 1.6,
  },
  settingsButton: {
    mt: '4',
    w: '100%',
    justifyContent: 'flex-start',
    gap: '2.5',
    borderRadius: '0.9rem',
    border: '1px solid var(--surface-line)',
    bg: 'var(--secondary-surface)',
    color: 'var(--text-main)',
    _hover: {
      bg: 'var(--secondary-surface-hover)',
    },
  },
  inlineIcon: {
    boxSize: '1rem',
  },
  settingsPanel: {
    mt: '4',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '4',
    borderRadius: '1rem',
    border: '1px solid var(--surface-line)',
    bg: 'var(--secondary-surface)',
    p: '3.5',
  },
  settingsTitle: {
    fontSize: 'sm',
    fontWeight: '600',
  },
  settingsCopy: {
    mt: '1',
    fontSize: 'xs',
    color: 'var(--text-muted)',
    lineHeight: 1.5,
  },
  switchTrack: {
    position: 'relative',
    flexShrink: 0,
    w: '3.35rem',
    h: '1.85rem',
    borderRadius: 'full',
    bg: 'var(--switch-track)',
    border: '1px solid var(--switch-track-border)',
    transition: 'background 180ms ease, border-color 180ms ease',
  },
  switchThumb: {
    position: 'absolute',
    top: '0.16rem',
    left: '0.16rem',
    w: '1.45rem',
    h: '1.45rem',
    borderRadius: 'full',
    bg: 'var(--switch-thumb)',
    boxShadow: '0 8px 18px rgba(0, 0, 0, 0.2)',
    transition: 'transform 180ms ease',
  },
}
